// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

// #include <Rcpp.h>
#include <RcppArmadillo.h>
#include <string.h>

using namespace Rcpp;
using namespace arma;

// corSubsetPairs
vec corSubsetPairs( const mat & Y, const vec & idxi, const vec & idxj);
RcppExport SEXP _decorate_corSubsetPairs(SEXP YSEXP, SEXP idxiSEXP, SEXP idxjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< vec >::type idxi(idxiSEXP);
    Rcpp::traits::input_parameter< vec >::type idxj(idxjSEXP);
    rcpp_result_gen = Rcpp::wrap(corSubsetPairs(Y, idxi, idxj));
    return rcpp_result_gen;
END_RCPP
}


// boxM
Rcpp::List boxM_fast(const arma::mat & Y, const arma::vec & group, const Rcpp::String & method );
RcppExport SEXP _decorate_boxM_fast(SEXP YSEXP, SEXP groupSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< vec >::type group(groupSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(boxM_fast(Y, group, method));
    return rcpp_result_gen;
END_RCPP
}


static const R_CallMethodDef CallEntries[] = {
    {"_decorate_corSubsetPairs", (DL_FUNC) &_decorate_corSubsetPairs, 3},
    {"_decorate_boxM_fast", (DL_FUNC) &_decorate_boxM_fast, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pinnacle(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
