# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boxM_fast <- function(Y, group, method) {
    .Call('_decorate_boxM_fast', PACKAGE = 'decorate', Y, group, method)
}

corSubsetPairs <- function(Y, idxi, idxj) {
    .Call('_decorate_corSubsetPairs', PACKAGE = 'decorate', Y, idxi, idxj)
}

